#copy .zshrc .vimrc .vim .config FastSyntaxHighlighting
# Have these settings apply to servers in my organization

env XDG_CONFIG_HOME=$HOME/my-conf
copy .config/fsh FastSyntaxHighlighting

# Setup zsh to read its files from my-conf/zsh
env ZDOTDIR=$HOME/my-conf/zsh
copy --dest my-conf/zsh/.zshrc .config/zsh/zshrc
copy --dest my-conf/zsh/.zprofile .zprofile
# If you use other zsh init files add them in a similar manner

# Setup vim to read its config from my-conf/vim
copy .vim
copy .config/vim/vimrc

