let g:ctrlp_extensions = ['mpc']
" Sheer awesomeness

set rtp+=/opt/homebrew/opt/fzf
let g:ale_linters = {'rust': ['analyzer']}
" Initialize configuration dictionary
let g:fzf_vim = {}
let g:fzf_vim.command_prefix = 'Fzf'

set clipboard=unnamed
set nocompatible
filetype on
filetype plugin on
filetype indent on
syntax on
set number
set cursorline
set shiftwidth=4
set tabstop=4
set expandtab
set incsearch
set ignorecase
set smartcase
set showcmd
set showmode
set showmatch
set hlsearch
set history=1000
set wildmenu
set wildmode=list:longest
set wildignore=*.docx,*.jpg,*.png,*.gif,*.pdf,*.pyc,*.exe,*.flv,*.img,*.xlsx
set scrolloff=15
let mapleader = "'"

nnoremap <Leader>m :CtrlPMpc<CR>
nnoremap <leader>w :w<CR>
nnoremap <leader>s <C-W><C-W>
nnoremap <leader>q :wq<CR>
nnoremap <leader>e :q<CR>

inoremap jh <Esc>

set termguicolors
colorscheme catppuccin_mocha

set autoread
set lazyredraw
set magic
set regexpengine=0
set smarttab

set ai
set si

set noerrorbells
set novisualbell
set t_vb=
set tm=500
set belloff=all

set foldmethod=syntax

nnoremap <Enter> za
au BufRead * normal zR

let g:airline_powerline_fonts = 1

let g:airline#extensions#tabline#enabled = 1

let g:airline_powerline_fonts = 1

let g:airline_section_c_only_filename = 1

"function! GetMusic()
"  redir => message
"  silent execute "CmusCurrent"
"  redir END
"  return message[1:-1]
"endfunction
"let g:airline_section_y = '%-0.70{GetMusic()}'
"let g:airline_section_b = 'wahoo'
let g:airline#extensions#battery#enabled = 1
