# enable fzf features
source <(fzf --zsh)

# load colors
autoload -U colors && colors

# pretty self explanatory names
setopt interactive_comments
setopt autocd
# custom prompt
setopt PROMPT_SUBST
PROMPT='%{$fg[green]%}%t %{$reset_color%}- %B%{$fg[blue]%}%n %b%{$reset_color%}- %{$fg[cyan]%}%~
%{$reset_color%}  '

source $(brew --prefix)/opt/zsh-vi-mode/share/zsh-vi-mode/zsh-vi-mode.plugin.zsh

# aliases
alias man="batman" # make syntax highlighted nicely
alias ls="ls -G -p" # make syntax highlighted nicely and add / to end of folder names
alias rustman="man -M ~/rustman" # custom man directory. has the rust book in a man page.
alias edconf="vim ~/.config/zsh/zshrc && source ~/.zshrc" # edit this file
alias sedconf="vim ~/.config/sketchybar/sketchybarrc && brew services restart sketchybar" # sketchybar config edit
alias bedconf="vim ~/.config/borders/bordersrc && brew services restart borders" # borders config edit
alias edcolor="vim ~/.config/colors.sh && brew services restart sketchybar && brew services restart borders" # color edit
alias aedconf="vim ~/.config/aerospace/aerospace.toml && aerospace reload-config" # aerospace config edit
alias mt="cmus-remote -u -Q | grep file" # cmus remote aliases
alias mn="cmus-remote -n -Q | grep file" # cmus remote aliases
alias mb="cmus-remote -r -Q | grep file" # cmus remote aliases
alias cr="cmus-remote" # cmus remote aliases
alias steam='wine "/Users/simonbowering/.wine/drive_c/Program Files (x86)/Steam/steam.exe"' #launch steam in wine
# name and clear function. clears then writes name
simon() {
    clear
    echo "$fg[red]███████╗$fg[blue]██╗$fg[magenta]███╗   ███╗$fg[cyan] ██████╗ $fg[green]███╗   ██╗";
    echo "$fg[red]██╔════╝$fg[blue]██║$fg[magenta]████╗ ████║$fg[cyan]██╔═══██╗$fg[green]████╗  ██║";
    echo "$fg[red]███████╗$fg[blue]██║$fg[magenta]██╔████╔██║$fg[cyan]██║   ██║$fg[green]██╔██╗ ██║";
    echo "$fg[red]╚════██║$fg[blue]██║$fg[magenta]██║╚██╔╝██║$fg[cyan]██║   ██║$fg[green]██║╚██╗██║";
    echo "$fg[red]███████║$fg[blue]██║$fg[magenta]██║ ╚═╝ ██║$fg[cyan]╚██████╔╝$fg[green]██║ ╚████║";
    echo "$fg[red]╚══════╝$fg[blue]╚═╝$fg[magenta]╚═╝     ╚═╝$fg[cyan] ╚═════╝ $fg[green]╚═╝  ╚═══╝";
}
alias clear="simon"
# lesspipe stuffz
PATH=$PATH:~/bin
fpath=$fpath:~/.fpath
lesspipe.sh | source /dev/stdin
# fast syntax highlighting
source ~/FastSyntaxHighlighting/fast-syntax-highlighting.plugin.zsh
# run name function
clear
